Version: 1.00

Logging:
    #main log - log created by the main application
    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO
    # this section defines how often a new log file will be created and how many backup files are stored
    time_rotating:
        when: 'D' # expected values: S-Seconds,M-Minutes,H-Hours,D-Days,W0-W6-Weekday (0=Monday),midnight-Rolls over at midnight
        interval: 1 # defines how often a rotation will be applied
        backupCount: 30 # defines how many backup files are stored (any extra files are being deleted)

Location:
    app_logs: logs

Email:
    #default settings for sending emails
    default_from_email: stas.rirak@mssm.edu
    send_to_emails: ['stasrirak.ms@gmail.com', 'stas.rirak@mssm.edu']
    send_emails: True # expected values: True, False
    url_len_show_in_subject: 50 # defines how many characters of the url will be shown in the subject of email


